default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: my_user
  password: stefanstefan2
  host: <%= ENV['IP'] %>

development:
  <<: *default
  database: my_app_development
  username: my_user
  password: stefanstefan2
  host: 127.0.0.1

test:
  <<: *default
  database: my_app_test
  username: my_user
  password: stefanstefan2
  host: 127.0.0.1

production:
  <<: *default
  database: my_app_production
  username: my_user
  password: stefanstefan2
